# @package logger
_target_: pytorch_lightning.loggers.NeptuneLogger
api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIyNDlmZWY0Zi01M2I2LTRiOTItYmEyZi1kYWM2OWE3MmJjYzQifQ=="
project: "alronz.bilal/crypto-kpa"
log_model_checkpoints: False