# @package task
defaults:
  - /dataset@_group_: default

# By default we turn off recursive instantiation, allowing the user to instantiate themselves at the appropriate times.
_recursive_: false

_target_: project.models.common.base_model.BaseModel
optimizer: ${optimizer}
scheduler: ${scheduler}