defaults: # loads default configs
  - dataset: default
  - task: baselines/default
  - optimizer: adamw
  - scheduler: linear_schedule_with_warmup
  - training: default
  - trainer: default
  - logger: neptune

experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
log: True
ignore_warnings: True # todo: check warnings before release